# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: plat4m
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ZDc1YjdhYjVlZTYwMTk0MDg4NGViZDAwYWQ1ZDU5ZmM2ZDhiYjMxZDdlZGE3YzFkYmE0ZDJlN2U4OTI4ODQ2ZmZkOWIwYzMzNTA5ZGQyMzJhMDc5YTFlYjYwNTZjM2Y3N2QzMTRiOTc5YjNkZTZlMmEzYWJiZGQyMzE0NjcwY2E=
